<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cd_review_list [
<!ELEMENT cd_review_list (cd_review*)>
<!ELEMENT cd_review (review, cd)>
<!ELEMENT review (#PCDATA)>
<!ELEMENT cd (author, title)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT title (#PCDATA)>
]>
<cd_review_list>
 <cd_review>
  <review>
   I heard all of the latest reports of the forthcoming which has been since     released, Silenoz said that it was going to be the most apocalyptic and bombastic CD. To be honest, I think it's more majestic, symphonic and grandiose. ...
  </review>
  <cd>
   <author>Dimmu Borgir</author>
   <title>Death Cult Armageddon</title>
  </cd>
 </cd_review>
 <cd_review>
  <review>
   Whoa, the Dutch team has changed quite a bit... From the beginning of the opening "Grip" you realise that the guitars and bass sound very modern, hm. Add the harsh voice of George Oosthoek and you have a completely un-atmospheric atmosphere, which...
  </review>
  <cd>
   <author>Orphanage</author>
   <title>Inside</title>
  </cd>
 </cd_review>
</cd_review_list>
