<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NEWSPAPER [
<!ELEMENT NEWSPAPER (ARTICLE+)>
<!ELEMENT ARTICLE (HEADLINE, BYLINE, BODY, NOTES)>
<!ELEMENT HEADLINE (#PCDATA)>
<!ELEMENT BYLINE (#PCDATA)>
<!ELEMENT BODY (#PCDATA)>
<!ELEMENT NOTES (#PCDATA)>

<!ATTLIST ARTICLE AUTHOR CDATA #REQUIRED>
<!ATTLIST ARTICLE DATE CDATA #IMPLIED>

<!ENTITY NEWSPAPER "Vervet Logic Times">
<!ENTITY PUBLISHER "Vervet Logic Press">
<!ENTITY COPYRIGHT "Copyright 1998 Vervet Logic Press">
]>
<NEWSPAPER>
<ARTICLE AUTHOR="PEPE" DATE="3_07_2020">
<HEADLINE>LINEA1</HEADLINE>
<BYLINE>LINEA2</BYLINE>
<BODY>LINEA3</BODY>
<NOTES>LINEA4</NOTES>
</ARTICLE>
<ARTICLE AUTHOR="MANOLO" DATE="4_08_2020">
<HEADLINE>LINEA1</HEADLINE>
<BYLINE>LINEA2</BYLINE>
<BODY>LINEA3</BODY>
<NOTES>LINEA4</NOTES>
</ARTICLE>
</NEWSPAPER>